"""Add time_slot to appointments

Revision ID: 4f799ebe7518
Revises: bdcf97c85af9
Create Date: 2025-11-18 02:25:59.807198

"""
from alembic import op
import sqlalchemy as sa


revision = '4f799ebe7518'
down_revision = 'bdcf97c85af9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('time_slot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'time_slot')
    # ### end Alembic commands ###
