"""Update patient schema - replace first_name last_name with name and add gender

Revision ID: bdcf97c85af9
Revises: 001
Create Date: 2025-11-18 00:03:03.768785

"""
from alembic import op
import sqlalchemy as sa


revision = 'bdcf97c85af9'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_idempotency_key'), 'appointments', ['idempotency_key'], unique=False)
    op.add_column('patients', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('patients', sa.Column('gender', sa.String(length=20), nullable=True))
    op.drop_column('patients', 'first_name')
    op.drop_column('patients', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'name')
    op.drop_index(op.f('ix_appointments_idempotency_key'), table_name='appointments')
    # ### end Alembic commands ###
