"""add_blood_group_to_patient

Revision ID: bf1694d1ff15
Revises: ef1a2b3c4d5e
Create Date: 2026-03-24 21:37:40.352251

"""
from alembic import op
import sqlalchemy as sa


revision = 'bf1694d1ff15'
down_revision = 'ef1a2b3c4d5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_appointment_check_in_code', 'appointments', ['check_in_code'], unique=False)
    op.add_column('patients', sa.Column('blood_group', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'blood_group')
    op.drop_index('ix_appointment_check_in_code', table_name='appointments')
    # ### end Alembic commands ###
