"""add_auth_and_clinic_models

Revision ID: ef0c817b12a1
Revises: bf1694d1ff15
Create Date: 2026-03-25 18:52:20.859584

"""
from alembic import op
import sqlalchemy as sa


revision = 'ef0c817b12a1'
down_revision = 'bf1694d1ff15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CLINIC', 'DOCTOR', 'PATIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clinics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('doctor_masters', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('doctor_masters', sa.Column('clinic_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'doctor_masters', ['user_id'])
    op.create_foreign_key(None, 'doctor_masters', 'clinics', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'doctor_masters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_masters', type_='foreignkey')
    op.drop_constraint(None, 'doctor_masters', type_='foreignkey')
    op.drop_constraint(None, 'doctor_masters', type_='unique')
    op.drop_column('doctor_masters', 'clinic_id')
    op.drop_column('doctor_masters', 'user_id')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
