"""Add check_in_code to appointments

Revision ID: ef1a2b3c4d5e
Revises: 4f799ebe7518
Create Date: 2026-03-24 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


revision = 'ef1a2b3c4d5e'
down_revision = '4f799ebe7518'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('check_in_code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_appointments_check_in_code'), 'appointments', ['check_in_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_check_in_code'), table_name='appointments')
    op.drop_column('appointments', 'check_in_code')
    # ### end Alembic commands ###
